### ISSUE TITLE
Did it support Intel Galileo?

### ISSUE THREAD

**Issue by hoangvanthien** [PaulStoffregen/CapacitiveSensor#13]
I got this error:

```
Arduino: 1.6.9 (Mac OS X), Board: "Intel® Galileo"

In file included from /Users/macbookair/Documents/Arduino/Timer/Timer.ino:1:0:
/Users/macbookair/Documents/Arduino/libraries/CapacitiveSensor/CapacitiveSensor.h:239:2: error: ‘IO_REG_TYPE’ does not name a type
/Users/macbookair/Documents/Arduino/libraries/CapacitiveSensor/CapacitiveSensor.h:240:11: error: ‘IO_REG_TYPE’ does not name a type
/Users/macbookair/Documents/Arduino/libraries/CapacitiveSensor/CapacitiveSensor.h:241:2: error: ‘IO_REG_TYPE’ does not name a type
/Users/macbookair/Documents/Arduino/libraries/CapacitiveSensor/CapacitiveSensor.h:242:11: error: ‘IO_REG_TYPE’ does not name a type
exit status 1
Error compiling for board Intel® Galileo.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

Even after I followed [this](https://communities.intel.com/thread/101102), it didn't work.

**Comment by PaulStoffregen** [comment]
I replied on the Intel forum.

I do not own a Galileo board.  I depend on board vendors and the community to contribute these hardware defs for other hardware which I do not personally own and spend my own time testing.  

Until someone does that, Galileo is unsupported.

My opinion is people within Intel really should do this work, if they wish for their products to integrate well with Arduino and be truly usable by the Arduino community.  If a board vendor, even Intel, it unwilling to do this work to have their products well supported, perhaps you should consider buying from a different vendor?
