### ISSUE TITLE
compile error with RF-Duino

### ISSUE THREAD

**Issue by m00ny** [PaulStoffregen/CapacitiveSensor#14]
Hi there,

First of all: CapacitiveSensor is the greatest way of implementing a touch-Sensor I've seen. There are a lot of schematics with discrete parts on the net, but using almost nothing but 2 pins of a µC is fantastic!

I'm trying to use CapSense on my project with the RF-Duino.
There's a problem at compile with Pin-bitmasks:

`/home/simon/Arduino/libraries/CapacitiveSensor-master/CapacitiveSensor.h:239:2: error: 'IO_REG_TYPE' does not name a type
  IO_REG_TYPE sBit;   // send pin's ports and bitmask
  ^
/home/simon/Arduino/libraries/CapacitiveSensor-master/CapacitiveSensor.h:240:11: error: 'IO_REG_TYPE' does not name a type
  volatile IO_REG_TYPE *sReg;
           ^
/home/simon/Arduino/libraries/CapacitiveSensor-master/CapacitiveSensor.h:241:2: error: 'IO_REG_TYPE' does not name a type
  IO_REG_TYPE rBit;    // receive pin's ports and bitmask
  ^
/home/simon/Arduino/libraries/CapacitiveSensor-master/CapacitiveSensor.h:242:11: error: 'IO_REG_TYPE' does not name a type
  volatile IO_REG_TYPE *rReg;
           ^
Fehler beim Kompilieren.`

How can they be found out?

Best regards,
m00ny

**Comment by PaulStoffregen** [comment]
Ask the RF-Duino developers to contribute them to this library (and others).
