### ISSUE TITLE
Capacitive Sensor - Intel Edison

### ISSUE THREAD

**Issue by pigcan** [PaulStoffregen/CapacitiveSensor#2]
Hi 
I was trying to use this library with Intel Edison Arduino Kit , but it  does not work.

In file included from CapacitiveSensor.ino:3:0:
/Users/pigcan/Documents/Arduino/libraries/CapacitiveSensor/CapacitiveSensor.h:97:3: error: 'IO_REG_TYPE' does not name a type
   IO_REG_TYPE sBit;   // send pin's ports and bitmask
   ^
/Users/pigcan/Documents/Arduino/libraries/CapacitiveSensor/CapacitiveSensor.h:98:12: error: 'IO_REG_TYPE' does not name a type
   volatile IO_REG_TYPE *sReg;
            ^
/Users/pigcan/Documents/Arduino/libraries/CapacitiveSensor/CapacitiveSensor.h:99:3: error: 'IO_REG_TYPE' does not name a type
   IO_REG_TYPE rBit;    // receive pin's ports and bitmask
   ^
/Users/pigcan/Documents/Arduino/libraries/CapacitiveSensor/CapacitiveSensor.h:100:12: error: 'IO_REG_TYPE' does not name a type
   volatile IO_REG_TYPE *rReg;
            ^

**Comment by PaulStoffregen** [comment]
I mean, I do not support Intel Edision.  But if someone contributes a patch, I'll merge it.

**Comment by sambaker** [comment]
@pigcan - do you still need this library for Edison? I have a copy of v0.4 that I've hacked around with to work on Edison (using C++ in Eclipse, not the Arduino IDE for edison) but it's not in good shape for a pull request, it's no longer compatible with Arduino. If you want to merge my changes in with the Arduino version and make it cross-platform I'm happy to share, I just don't have time to finish it up myself right now.

The edison GPIO access is much slower than Arduino so this library runs pretty slowly but it's usable if you just have a few capacitive sensors.

**Comment by PaulStoffregen** [comment]
I'd like to merge support for Edison, but I really must maintain Arduino compatibility for all other boards.

If you can't get the code cleaned up, maybe just post what you have here?  Or post it anywhere else that's durable long-term and post a link here?  Maybe someone else will clean it up?

**Comment by sambaker** [comment]
I've created a fork, I'll try to get a reasonable merge committed to it in the next couple of days and post back here with the info.

**Comment by sambaker** [comment]
Well, this never happened - we ended up moving the sensor code to an arduino. Paul's arduino version was well enough commented that I was able to get data back by replacing the arduino writes with calls to the mraa library - however the issues were, slow responses and difficult to get meaningful values. An alternative is to use an adafruit trinket pro or similar and wire that to the edison over i2c. That worked for me.

**Comment by PaulStoffregen** [comment]
If anyone can figure out the direct pin defines to make this work on Edison, I'd be happy to add them.

**Comment by jprunier** [comment]
Compatibility with edison still  not available?
Thank you,

**Comment by PaulStoffregen** [comment]
Nope, not until someone contributes it....

That's how open source works.  Maybe you'd like to give a try?  Send a pull request if you manage to get it working.

**Comment by PaulStoffregen** [comment]
Or maybe ask Intel to look into this issue?

Their people did write these macros for Curie used on Arduino 101.  I merged their code into a couple libraries I maintain.  If they do the same for Edison, I'd be happy to merge their code (even it's overly large, like they did for Curie).  But I'm not going to put engineering time into developing this from scratch for their product.  Either they or someone inspired contributor needs to do the legwork.  That's how open source software is.

**Comment by jprunier** [comment]
Understand, thx for your reply. If I have time to devlopp that I will share.I did a test with an Uno and it compile fine (for sure^^). So easier to design my solution with ant Uno. Thank Paul for you open source work.

**Comment by q2dg** [comment]
Well, now Edison is officially abandoned, this issue could be closed...

**Comment by PaulStoffregen** [comment]
ok
