### ISSUE TITLE
CapacitiveSensor + interrupt

### ISSUE THREAD

**Issue by HugoDel** [PaulStoffregen/CapacitiveSensor#25]
I don't know if it's possible but can I use this library with an interrupt? I want to put my Arduino to sleep with the Low-power library and wake it only if a touch is detected.

**Comment by PaulStoffregen** [comment]
1: Github issues are not the place to ask project questions.  Post on the Arduino forum.  At the very least, tell people (on the forum) which board you have.  Other project details in your message might also help people give you more useful advice.

2: This lib doesn't support interrupts.
