### ISSUE TITLE
Need help with understanding the CapacitiveSensor circuit diagram

### ISSUE THREAD

**Issue by Camerutttt** [PaulStoffregen/CapacitiveSensor#27]
Hi, I need help with understanding the circuit diagram from this link: https://playground.arduino.cc/Main/CapacitiveSensor?from=Main.CapSense

As of now, this is the schematic I drew from what I understand: https://imgur.com/YBvBupJ

I know it is wrong since there are 2 capacitors, but I do not know where should the other capacitor be connected to.

**Comment by PaulStoffregen** [comment]
This is the wrong place to ask.  Use the Arduino forum.

This is only for reporting well-confirmed bugs.

**Comment by Camerutttt** [comment]
Isnt the document written by you though?
