### ISSUE TITLE
Support for TeensyLC?

### ISSUE THREAD

**Issue by hoosierEE** [PaulStoffregen/CapacitiveSensor#8]
Is this coming?

**Comment by PaulStoffregen** [comment]
Teensy-LC had vastly superior touchRead(pin).

**Comment by hoosierEE** [comment]
Nice, I had already started using touchRead(), but did not know it was superior.  

By the way, is touchRead() documented anywhere (besides the comments in [touch.c](https://github.com/PaulStoffregen/cores/blob/d5a1b9745bc2935d0aa09294fe9e98b475b1e8cf/teensy3/touch.c))?  Looks like there are some tradeoffs between the capacity being measured and the measurement's duration, but it's a little vague.
