### ISSUE TITLE
license file

### ISSUE THREAD

**Issue by hanabanana** [PaulStoffregen/CapacitiveSensor#9]
Hi Paul,

What is the license used for this library? I cannot find it anywhere other than the one line of "copyright..." in the source files.

Thanks.

**Comment by PaulStoffregen** [comment]
I don't know.  Paul Badger originally wrote this library.  I only maintain it now.

**Comment by PaulStoffregen** [comment]
Good news.  I was able to contact Paul Badger.  He said the MIT license applies.

I've updated the code with https://github.com/PaulStoffregen/CapacitiveSensor/commit/2faac421e1540d40bcfb3933d46c93b4fd6c01d7
